# Generated by Django 4.0.3 on 2022-04-09 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_userWallet', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='host',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
