# Generated by Django 4.0.3 on 2022-04-09 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_userWallet', '0005_remove_userwallet_host_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionhistory',
            name='added_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='updateAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='userWallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
