# Generated by Django 4.0.3 on 2022-04-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_userWallet', '0006_usertransactionhistory_added_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
